### ISSUE TITLE
Error: Timeout

### ISSUE THREAD

**Issue by mitmul** [chainer/pg-dl-tutorial#1]
I just see this error in the page ciFAR-10の学習：総結合層を使った学習 after clicking the `Run` button.

```
Traceback (most recent call last):
  File "/var/sandbox/main.py", line 86, in <module>
    trainer.run()
  File "/usr/local/lib/python2.7/dist-packages/chainer/training/trainer.py", line 266, in run
    update()
  File "/usr/local/lib/python2.7/dist-packages/chainer/training/updater.py", line 170, in update
    self.update_core()
  File "/usr/local/lib/python2.7/dist-packages/chainer/training/updater.py", line 182, in update_core
    optimizer.update(loss_func, *in_vars)
  File "/usr/local/lib/python2.7/dist-packages/chainer/optimizer.py", line 392, in update
    loss = lossfun(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/chainer/links/model/classifier.py", line 68, in __call__
    self.loss = self.lossfun(self.y, t)
  File "/usr/local/lib/python2.7/dist-packages/chainer/functions/loss/softmax_cross_entropy.py", line 169, in softmax_cross_entropy
    return SoftmaxCrossEntropy(use_cudnn, normalize, cache_score)(x, t)
Error: Timeout
```

**Comment by ando-takahiro** [comment]
I got Timeout on page 2/11.  Please give more time when the maintainer has time.  Thanks.

**Comment by kmaehashi** [comment]
MNIST example (`001introduction/022/`) also timed out when using `epoch = 5` as instructed.
